from __future__ import annotations

import logging
from contextlib import contextmanager
from datetime import datetime, timezone
from typing import Any, Dict, Iterator, List, Optional
from uuid import uuid4

import psycopg
from psycopg.rows import dict_row

from models import ExecutionResult, Position


logger = logging.getLogger(__name__)


class UnresolvedOrderError(RuntimeError):
    """Raised when a pair has an order whose external outcome is not known."""


class StateStore:
    """PostgreSQL-backed durable bot state.

    Positions, trades, equity, metadata, and order intents are committed to one
    PostgreSQL database. An order intent is persisted before an external order
    is sent. If the process dies while a venue request is in flight, the
    unresolved intent prevents a duplicate order after restart until the user
    reconciles the venue account.
    """

    def __init__(self, config):
        if not config.postgres_dsn and (
            not config.postgres_user
            or not config.postgres_password
            or not config.postgres_database
        ):
            raise ValueError(
                "Set POSTGRES_DSN or POSTGRES_USER, POSTGRES_PASSWORD, and POSTGRES_DATABASE"
            )
        if config.postgres_dsn:
            self._conn = psycopg.connect(config.postgres_dsn, row_factory=dict_row)
        else:
            self._conn = psycopg.connect(
                host=config.postgres_host,
                port=config.postgres_port,
                user=config.postgres_user,
                password=config.postgres_password,
                dbname=config.postgres_database,
                sslmode=config.postgres_sslmode,
                row_factory=dict_row,
            )
        self._init_schema()
        logger.info(
            "StateStore connected to PostgreSQL %s:%s/%s",
            config.postgres_host,
            config.postgres_port,
            config.postgres_database,
        )

    def _init_schema(self) -> None:
        statements = [
            """
            CREATE TABLE IF NOT EXISTS positions (
                pair_id VARCHAR(128) PRIMARY KEY,
                venue VARCHAR(32) NOT NULL,
                symbol VARCHAR(255) NOT NULL,
                qty NUMERIC(38, 18) NOT NULL CHECK (qty > 0),
                entry_price NUMERIC(38, 18) NOT NULL CHECK (entry_price >= 0),
                stop_loss NUMERIC(38, 18) NOT NULL DEFAULT 0,
                take_profit NUMERIC(38, 18) NOT NULL DEFAULT 0,
                opened_at TIMESTAMPTZ NOT NULL
            )
            """,
            """
            CREATE TABLE IF NOT EXISTS trades (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                ts TIMESTAMPTZ NOT NULL,
                pair_id VARCHAR(128) NOT NULL,
                venue VARCHAR(32) NOT NULL,
                symbol VARCHAR(255) NOT NULL,
                side VARCHAR(8) NOT NULL CHECK (side IN ('buy', 'sell')),
                qty NUMERIC(38, 18) NOT NULL CHECK (qty > 0),
                price NUMERIC(38, 18) NOT NULL CHECK (price >= 0),
                fee NUMERIC(38, 18) NOT NULL DEFAULT 0,
                order_id VARCHAR(255)
            )
            """,
            "CREATE INDEX IF NOT EXISTS idx_trades_ts ON trades (ts DESC)",
            """
            CREATE TABLE IF NOT EXISTS meta (
                "key" VARCHAR(128) PRIMARY KEY,
                value TEXT
            )
            """,
            """
            CREATE TABLE IF NOT EXISTS equity_history (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                ts TIMESTAMPTZ NOT NULL,
                equity NUMERIC(38, 18) NOT NULL
            )
            """,
            "CREATE INDEX IF NOT EXISTS idx_equity_history_ts ON equity_history (ts DESC)",
            """
            CREATE TABLE IF NOT EXISTS orders (
                client_order_id UUID PRIMARY KEY,
                pair_id VARCHAR(128) NOT NULL,
                venue VARCHAR(32) NOT NULL,
                symbol VARCHAR(255) NOT NULL,
                side VARCHAR(8) NOT NULL CHECK (side IN ('buy', 'sell')),
                requested_qty NUMERIC(38, 18) NOT NULL CHECK (requested_qty > 0),
                requested_price NUMERIC(38, 18) NOT NULL CHECK (requested_price >= 0),
                status VARCHAR(16) NOT NULL CHECK (status IN ('pending', 'filled', 'rejected', 'unknown')),
                broker_order_id VARCHAR(255),
                filled_qty NUMERIC(38, 18),
                filled_price NUMERIC(38, 18),
                fee NUMERIC(38, 18),
                error TEXT,
                created_at TIMESTAMPTZ NOT NULL,
                updated_at TIMESTAMPTZ NOT NULL
            )
            """,
            "CREATE INDEX IF NOT EXISTS idx_orders_pair_created ON orders (pair_id, created_at DESC)",
            """
            CREATE UNIQUE INDEX IF NOT EXISTS idx_orders_one_unresolved_per_pair
            ON orders (pair_id) WHERE status IN ('pending', 'unknown')
            """,
        ]

        with self._transaction() as cur:
            for statement in statements:
                cur.execute(statement)

    @contextmanager
    def _transaction(self) -> Iterator[Any]:
        try:
            with self._conn.cursor() as cur:
                yield cur
            self._conn.commit()
        except Exception:
            self._conn.rollback()
            raise

    def _execute(self, sql: str, params: tuple = ()) -> int:
        with self._transaction() as cur:
            cur.execute(sql, params)
            return cur.rowcount

    def _query(self, sql: str, params: tuple = ()) -> List[Dict[str, Any]]:
        # psycopg starts a transaction for SELECT as well. Commit the read so a
        # dashboard connection never sits "idle in transaction" indefinitely.
        with self._transaction() as cur:
            cur.execute(sql, params)
            return list(cur.fetchall())

    @staticmethod
    def _timestamp(value: str | datetime) -> datetime:
        if isinstance(value, datetime):
            return value if value.tzinfo else value.replace(tzinfo=timezone.utc)

        parsed = datetime.fromisoformat(value)
        return parsed if parsed.tzinfo else parsed.replace(tzinfo=timezone.utc)

    def _row_to_position(self, row: Dict[str, Any]) -> Position:
        opened_at = row["opened_at"]
        if isinstance(opened_at, datetime):
            opened_at = opened_at.isoformat()

        return Position(
            pair_id=row["pair_id"],
            venue=row["venue"],
            symbol=row["symbol"],
            qty=float(row["qty"]),
            entry_price=float(row["entry_price"]),
            stop_loss=float(row["stop_loss"] or 0.0),
            take_profit=float(row["take_profit"] or 0.0),
            opened_at=opened_at,
        )

    # --- Positions -------------------------------------------------------

    def get_position(self, pair_id: str) -> Optional[Position]:
        rows = self._query("SELECT * FROM positions WHERE pair_id = %s", (pair_id,))
        return self._row_to_position(rows[0]) if rows else None

    def upsert_position(self, pos: Position) -> None:
        self._execute(
            """
            INSERT INTO positions (
                pair_id, venue, symbol, qty, entry_price, stop_loss, take_profit, opened_at
            ) VALUES (%s, %s, %s, %s, %s, %s, %s, %s)
            ON CONFLICT (pair_id) DO UPDATE SET
                venue = EXCLUDED.venue,
                symbol = EXCLUDED.symbol,
                qty = EXCLUDED.qty,
                entry_price = EXCLUDED.entry_price,
                stop_loss = EXCLUDED.stop_loss,
                take_profit = EXCLUDED.take_profit,
                opened_at = EXCLUDED.opened_at
            """,
            (
                pos.pair_id,
                pos.venue,
                pos.symbol,
                pos.qty,
                pos.entry_price,
                pos.stop_loss,
                pos.take_profit,
                self._timestamp(pos.opened_at),
            ),
        )

    def delete_position(self, pair_id: str) -> None:
        self._execute("DELETE FROM positions WHERE pair_id = %s", (pair_id,))

    def get_positions_by_venue(self, venue: str) -> List[Position]:
        rows = self._query("SELECT * FROM positions WHERE venue = %s", (venue,))
        return [self._row_to_position(row) for row in rows]

    def get_all_positions(self) -> List[Position]:
        return [self._row_to_position(row) for row in self._query("SELECT * FROM positions")]

    # --- Orders and idempotency -----------------------------------------

    def create_order_intent(
        self,
        *,
        pair_id: str,
        venue: str,
        symbol: str,
        side: str,
        qty: float,
        price: float,
    ) -> str:
        if side not in {"buy", "sell"}:
            raise ValueError("Order side must be 'buy' or 'sell'")
        if qty <= 0 or price < 0:
            raise ValueError("Order quantity must be positive and price cannot be negative")

        if self.has_unresolved_order(pair_id):
            raise UnresolvedOrderError(
                f"{pair_id} has an unresolved order; reconcile it before trading again"
            )

        client_order_id = str(uuid4())
        now = datetime.now(timezone.utc)
        try:
            self._execute(
                """
                INSERT INTO orders (
                    client_order_id, pair_id, venue, symbol, side, requested_qty,
                    requested_price, status, created_at, updated_at
                ) VALUES (%s, %s, %s, %s, %s, %s, %s, 'pending', %s, %s)
                """,
                (client_order_id, pair_id, venue, symbol, side, qty, price, now, now),
            )
        except psycopg.errors.UniqueViolation as exc:
            raise UnresolvedOrderError(
                f"{pair_id} has an unresolved order; reconcile it before trading again"
            ) from exc

        return client_order_id

    def has_unresolved_order(self, pair_id: str) -> bool:
        rows = self._query(
            "SELECT 1 FROM orders WHERE pair_id = %s AND status IN ('pending', 'unknown') LIMIT 1",
            (pair_id,),
        )
        return bool(rows)

    def get_unresolved_orders(self) -> List[Dict[str, Any]]:
        return self._query(
            """
            SELECT * FROM orders WHERE status IN ('pending', 'unknown')
            ORDER BY created_at ASC
            """
        )

    def mark_order_rejected(self, client_order_id: str, error: str) -> None:
        self._execute(
            """
            UPDATE orders SET status = 'rejected', error = %s, updated_at = %s
            WHERE client_order_id = %s AND status = 'pending'
            """,
            (error[:4000], datetime.now(timezone.utc), client_order_id),
        )

    def mark_order_unknown(self, client_order_id: str, error: str) -> None:
        self._execute(
            """
            UPDATE orders SET status = 'unknown', error = %s, updated_at = %s
            WHERE client_order_id = %s AND status = 'pending'
            """,
            (error[:4000], datetime.now(timezone.utc), client_order_id),
        )

    def complete_entry(
        self, client_order_id: str, pos: Position, result: ExecutionResult, ts: str
    ) -> None:
        if result.qty <= 0:
            raise ValueError("Cannot complete an entry with a zero fill")

        with self._transaction() as cur:
            cur.execute(
                """
                UPDATE orders
                SET status = 'filled', broker_order_id = %s, filled_qty = %s,
                    filled_price = %s, fee = %s, updated_at = %s
                WHERE client_order_id = %s AND status = 'pending'
                """,
                (
                    result.order_id or None,
                    result.qty,
                    result.price,
                    result.fee,
                    datetime.now(timezone.utc),
                    client_order_id,
                ),
            )
            if cur.rowcount != 1:
                raise UnresolvedOrderError(
                    f"Entry order {client_order_id} is not pending and cannot be completed"
                )

            cur.execute(
                """
                INSERT INTO positions (
                    pair_id, venue, symbol, qty, entry_price, stop_loss, take_profit, opened_at
                ) VALUES (%s, %s, %s, %s, %s, %s, %s, %s)
                ON CONFLICT (pair_id) DO UPDATE SET
                    venue = EXCLUDED.venue,
                    symbol = EXCLUDED.symbol,
                    qty = EXCLUDED.qty,
                    entry_price = EXCLUDED.entry_price,
                    stop_loss = EXCLUDED.stop_loss,
                    take_profit = EXCLUDED.take_profit,
                    opened_at = EXCLUDED.opened_at
                """,
                (
                    pos.pair_id,
                    pos.venue,
                    pos.symbol,
                    pos.qty,
                    pos.entry_price,
                    pos.stop_loss,
                    pos.take_profit,
                    self._timestamp(pos.opened_at),
                ),
            )
            self._insert_trade(cur, ts, pos, "buy", result)

    def complete_exit(
        self, client_order_id: str, pos: Position, result: ExecutionResult, ts: str
    ) -> float:
        if result.qty <= 0:
            raise ValueError("Cannot complete an exit with a zero fill")
        if result.qty > pos.qty * 1.000001:
            raise ValueError("Venue reported an exit fill larger than the tracked position")

        remaining_qty = max(0.0, pos.qty - result.qty)
        if remaining_qty <= max(1e-12, pos.qty * 1e-9):
            remaining_qty = 0.0

        with self._transaction() as cur:
            cur.execute(
                """
                UPDATE orders
                SET status = 'filled', broker_order_id = %s, filled_qty = %s,
                    filled_price = %s, fee = %s, updated_at = %s
                WHERE client_order_id = %s AND status = 'pending'
                """,
                (
                    result.order_id or None,
                    result.qty,
                    result.price,
                    result.fee,
                    datetime.now(timezone.utc),
                    client_order_id,
                ),
            )
            if cur.rowcount != 1:
                raise UnresolvedOrderError(
                    f"Exit order {client_order_id} is not pending and cannot be completed"
                )

            if remaining_qty:
                cur.execute(
                    "UPDATE positions SET qty = %s WHERE pair_id = %s",
                    (remaining_qty, pos.pair_id),
                )
            else:
                cur.execute("DELETE FROM positions WHERE pair_id = %s", (pos.pair_id,))

            self._insert_trade(cur, ts, pos, "sell", result)

        return remaining_qty

    # --- Trades ----------------------------------------------------------

    def _insert_trade(
        self, cur: Any, ts: str, pos: Position, side: str, result: ExecutionResult
    ) -> None:
        cur.execute(
            """
            INSERT INTO trades (ts, pair_id, venue, symbol, side, qty, price, fee, order_id)
            VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s)
            """,
            (
                self._timestamp(ts),
                pos.pair_id,
                pos.venue,
                pos.symbol,
                side,
                result.qty,
                result.price,
                result.fee,
                result.order_id or None,
            ),
        )

    def add_trade(
        self,
        ts: str,
        pair_id: str,
        venue: str,
        symbol: str,
        side: str,
        qty: float,
        price: float,
        fee: float,
        order_id: str,
    ) -> None:
        pos = Position(pair_id=pair_id, venue=venue, symbol=symbol, qty=qty, entry_price=price)
        result = ExecutionResult(qty=qty, price=price, fee=fee, order_id=order_id)
        with self._transaction() as cur:
            self._insert_trade(cur, ts, pos, side, result)

    def get_recent_trades(self, limit: int = 50) -> List[Dict[str, Any]]:
        return self._query("SELECT * FROM trades ORDER BY id DESC LIMIT %s", (limit,))

    # --- Equity history --------------------------------------------------

    def record_equity(self, ts: str, equity: float) -> None:
        self._execute(
            "INSERT INTO equity_history (ts, equity) VALUES (%s, %s)",
            (self._timestamp(ts), equity),
        )

    def get_equity_history(self, limit: int = 2000) -> List[Dict[str, Any]]:
        rows = self._query(
            "SELECT ts, equity FROM equity_history ORDER BY id DESC LIMIT %s", (limit,)
        )
        rows.reverse()
        return rows

    # --- Meta ------------------------------------------------------------

    def get_meta(self, key: str, default: Optional[str] = None) -> Optional[str]:
        rows = self._query('SELECT value FROM meta WHERE "key" = %s', (key,))
        return rows[0]["value"] if rows and rows[0]["value"] is not None else default

    def set_meta(self, key: str, value: str) -> None:
        self._execute(
            """
            INSERT INTO meta ("key", value) VALUES (%s, %s)
            ON CONFLICT ("key") DO UPDATE SET value = EXCLUDED.value
            """,
            (key, value),
        )

    def close(self) -> None:
        try:
            self._conn.close()
        except Exception:  # pragma: no cover - best effort on shutdown
            pass
