-- PostgreSQL schema for the trading bot. StateStore applies the same schema
-- automatically; this file exists for database review and managed deployments.

CREATE TABLE IF NOT EXISTS positions (
    pair_id VARCHAR(128) PRIMARY KEY,
    venue VARCHAR(32) NOT NULL,
    symbol VARCHAR(255) NOT NULL,
    qty NUMERIC(38, 18) NOT NULL CHECK (qty > 0),
    entry_price NUMERIC(38, 18) NOT NULL CHECK (entry_price >= 0),
    stop_loss NUMERIC(38, 18) NOT NULL DEFAULT 0,
    take_profit NUMERIC(38, 18) NOT NULL DEFAULT 0,
    opened_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS trades (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ts TIMESTAMPTZ NOT NULL,
    pair_id VARCHAR(128) NOT NULL,
    venue VARCHAR(32) NOT NULL,
    symbol VARCHAR(255) NOT NULL,
    side VARCHAR(8) NOT NULL CHECK (side IN ('buy', 'sell')),
    qty NUMERIC(38, 18) NOT NULL CHECK (qty > 0),
    price NUMERIC(38, 18) NOT NULL CHECK (price >= 0),
    fee NUMERIC(38, 18) NOT NULL DEFAULT 0,
    order_id VARCHAR(255)
);
CREATE INDEX IF NOT EXISTS idx_trades_ts ON trades (ts DESC);

CREATE TABLE IF NOT EXISTS meta (
    "key" VARCHAR(128) PRIMARY KEY,
    value TEXT
);

CREATE TABLE IF NOT EXISTS equity_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ts TIMESTAMPTZ NOT NULL,
    equity NUMERIC(38, 18) NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_equity_history_ts ON equity_history (ts DESC);

CREATE TABLE IF NOT EXISTS orders (
    client_order_id UUID PRIMARY KEY,
    pair_id VARCHAR(128) NOT NULL,
    venue VARCHAR(32) NOT NULL,
    symbol VARCHAR(255) NOT NULL,
    side VARCHAR(8) NOT NULL CHECK (side IN ('buy', 'sell')),
    requested_qty NUMERIC(38, 18) NOT NULL CHECK (requested_qty > 0),
    requested_price NUMERIC(38, 18) NOT NULL CHECK (requested_price >= 0),
    status VARCHAR(16) NOT NULL CHECK (status IN ('pending', 'filled', 'rejected', 'unknown')),
    broker_order_id VARCHAR(255),
    filled_qty NUMERIC(38, 18),
    filled_price NUMERIC(38, 18),
    fee NUMERIC(38, 18),
    error TEXT,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_orders_pair_created ON orders (pair_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_orders_broker_order_id ON orders (broker_order_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_orders_one_unresolved_per_pair
ON orders (pair_id) WHERE status IN ('pending', 'unknown');
